### ISSUE TITLE
More leaderboard

### ISSUE THREAD

**Issue by lycvlearn** [LiuYuML/NT-VOT211#1]
I noticed that your leaderboard on the EvalAI, why not set up a leaderboard on the paper with code?

**Comment by LiuYuML** [comment]
Thank you for your input. We will keep you informed, update our official page, and close this issue once they are resolved. 
Inspiring profile pic by the way😄.

**Comment by LiuYuML** [comment]
> I noticed that your leaderboard on the EvalAI, why not set up a leaderboard on the paper with code?

we have set up a new leaderboard on [papers with code](https://paperswithcode.com/sota/video-object-tracking-on-nv-vot211?metric=Precision)
